### ISSUE TITLE
Select All table header (and checkbox)

### ISSUE THREAD

**Issue by afercia** [rmccue/new-list-tables#1]
Currently, there's no "Select All" checkbox in the table headers. The current rendered markup is:
`<th class="column-cb check-column"></th>`
Whether or not the checkbox is going to be added, the table header needs some semantics and accessibility improvements.

- no checkbox: then the table header shouldn't be a `th` element because it shouldn't establish a relationship with all the cells in that column; screen reader would announce "Select All" as the "title" of each checkbox in the rows, while they are intended to select only their own row. This cell should be a `td`, see https://core.trac.wordpress.org/ticket/32892 and https://core.trac.wordpress.org/ticket/31654

- checkbox: even if the checkbox is going to be added, the cell should be a `td`; the checkbox should be properly labeled

**Comment by rmccue** [comment]
For now, the checkboxes aren't actually useful, so there's no way to add a select-all checkbox. Will fix that in the future, but for now, we can change to `td`
