### ISSUE TITLE
Improve the usage of the buttons CSS classes

### ISSUE THREAD

**Issue by afercia** [rmccue/new-list-tables#10]
The `button-secondary` CSS class is deprecated and still in WP core just for backwards compatibility reasons. 

The buttons CSS classes are "stackable", that means the base class is `button` and then other classes can be added as modifiers.

Worth noting, using only the `button-secondary` CSS class results in a wrong focus style applied to buttons and buttons are not responsive (they should become bigger in the responsive view).

For reference, see the comment in the `wp-includes/css/buttons.css` file.

**Comment by rmccue** [comment]
I _think_ this code was taken directly from `WP_Comments_List_Table`? Easy enough to fix anyway.

**Comment by afercia** [comment]
Yep, a while ago core was still using `button-secondary` in a few places, see https://core.trac.wordpress.org/ticket/37138
