### ISSUE TITLE
what's the status on this project?

### ISSUE THREAD

**Issue by aurovrata** [rmccue/new-list-tables#27]
The last update on this project is 10 months old.  Is it being superseded by another project?

**Comment by Mte90** [comment]
I guess that no the devs are more focused on Gutenberg...

**Comment by jonathanbossenger** [comment]
I think the keyword is in the description

"is a React-based **prototyping** area for ideas"

**Comment by aurovrata** [comment]
keyword to what?  Regardless of prototyping, the last submit time is more relevant to answer the question

**Comment by kadamwhite** [comment]
I'm not clear the extent to which @rmccue ever intended for this to be a long-lived project; it was a demonstration of the capabilities of the API for use with this sort of UI, and did not engender enough interest in the broader WordPress core contributor community to become a priority. I would second what @jonathanbossenger has suggested, that this should be considered a one-off prototype and not a project that will see further development.
